In [19]:
from sklearn.linear_model import LogisticRegression
import pandas as pd

fire = pd.read_csv('day_weather_firecount.csv', encoding = 'euc-kr')
fire.head(50)

Unnamed: 0  area_code area        date  max_temp  day_rain  max_wind  \
0            0         90   강원  2011-01-01       1.7       1.8       6.3   
1            1         90   강원  2011-01-02       6.1       1.4       4.1   
2            2         90   강원  2011-01-03       3.8       8.8       3.3   
3            3         90   강원  2011-01-04       6.3       0.0       3.9   
4            4         90   강원  2011-01-05       3.8       0.0       7.7   
5            5         90   강원  2011-01-06       0.8       0.0       5.0   
6            6         90   강원  2011-01-07       4.2       0.0       4.5   
7            7         90   강원  2011-01-08       3.1       0.0       8.6   
8            8         90   강원  2011-01-09       1.9       0.0       7.1   
9            9         90   강원  2011-01-10       1.0       0.0       4.3   
10          10         90   강원  2011-01-11       2.1       0.0       7.5   
11          11         90   강원  2011-01-12      -0.4       0.0       6.3   
12          12         90   강원  2011-01-13       1.6       0.0       4.5   
13          13         90   강원  2011-01-14       3.4       0.0       6.0   
14          14         90   강원  2011-01-15      -1.5       0.0      10.0   
15          15         90   강원  2011-01-16      -2.0       0.0       6.1   
16          16         90   강원  2011-01-17       1.4       0.0       7.0   
17          17         90   강원  2011-01-18       1.2       0.0       6.0   
18          18         90   강원  2011-01-19       1.3       0.0       6.7   
19          19         90   강원  2011-01-20      -0.7       0.0       5.8   
20          20         90   강원  2011-01-21       2.3       0.0       5.0   
21          21         90   강원  2011-01-22       3.7       0.0       6.7   
22          22         90   강원  2011-01-23       2.6       0.0       4.1   
23          23         90   강원  2011-01-24       1.1       0.0       5.5   
24          24         90   강원  2011-01-25       1.8       0.0       7.6   
25          25         90   강원  2011-01-26       1.8       0.0       9.5   
26          26         90   강원  2011-01-27       0.9       0.0       4.7   
27          27         90   강원  2011-01-28       0.5       0.0       6.8   
28          28         90   강원  2011-01-29      -2.1       0.0       9.0   
29          29         90   강원  2011-01-30      -2.1       0.0       5.3   
30          30         90   강원  2011-01-31       5.6       0.0       5.2   
31          31         90   강원  2011-02-01       7.6       0.0       4.6   
32          32         90   강원  2011-02-02      11.8       0.0       6.0   
33          33         90   강원  2011-02-03       9.8       0.0       7.0   
34          34         90   강원  2011-02-04       8.1       0.0       6.3   
35          35         90   강원  2011-02-05       6.9       0.0       5.2   
36          36         90   강원  2011-02-06       8.8       0.0       8.5   
37          37         90   강원  2011-02-07       6.0       0.0       5.2   
38          38         90   강원  2011-02-08       4.2       0.0       8.7   
39          39         90   강원  2011-02-09       3.7       0.0       8.0   
40          40         90   강원  2011-02-10       0.7       1.3       3.8   
41          41         90   강원  2011-02-11       0.9      33.5       4.5   
42          42         90   강원  2011-02-12      -1.0       9.8       7.4   
43          43         90   강원  2011-02-13       0.4       0.0       3.5   
44          44         90   강원  2011-02-14      -0.4      18.1       5.4   
45          45         90   강원  2011-02-15       5.7       0.0       3.7   
46          46         90   강원  2011-02-16       8.3       0.0       3.7   
47          47         90   강원  2011-02-17       4.4       0.0       5.7   
48          48         90   강원  2011-02-18       6.4       0.0       4.3   
49          49         90   강원  2011-02-19      12.1       0.0       4.0   

    min_humidity  counts  
0           31.0     0.0  
1           22.0     0.0  
2           59.0     0.0  
3           20.0   

In [20]:
fire.shape

(342995, 9)

In [21]:
fire_ml = fire[['area_code','date','max_temp','day_rain','max_wind','min_humidity','counts']]

In [10]:
from sklearn.preprocessing import OneHotEncoder


In [22]:
fire['area_code'].unique()

array([ 90,  93,  95,  98,  99, 100, 101, 102, 104, 105, 106, 108, 112,
       114, 115, 119, 121, 127, 129, 130, 131, 133, 135, 136, 137, 138,
       140, 143, 146, 152, 155, 156, 159, 162, 165, 168, 169, 170, 172,
       174, 175, 176, 177, 184, 185, 188, 189, 192, 201, 202, 203, 211,
       212, 216, 217, 221, 226, 232, 235, 236, 238, 239, 243, 244, 245,
       247, 248, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
       262, 263, 264, 266, 268, 271, 272, 273, 276, 277, 278, 279, 281,
       283, 284, 285, 288, 289, 294, 295], dtype=int64)

In [25]:
fire_ml.head()

area_code        date  max_temp  day_rain  max_wind  min_humidity  counts
0         90  2011-01-01       1.7       1.8       6.3          31.0     0.0
1         90  2011-01-02       6.1       1.4       4.1          22.0     0.0
2         90  2011-01-03       3.8       8.8       3.3          59.0     0.0
3         90  2011-01-04       6.3       0.0       3.9          20.0     0.0
4         90  2011-01-05       3.8       0.0       7.7          28.0     0.0

In [26]:
fire_ml.tail()

area_code        date  max_temp  day_rain  max_wind  min_humidity  \
342990        295  2020-12-27       6.0       7.8       1.8          62.0   
342991        295  2020-12-28      11.5       0.0       2.0          60.0   
342992        295  2020-12-29      11.2       6.6       3.0          59.0   
342993        295  2020-12-30       1.6       0.6       7.3          43.0   
342994        295  2020-12-31       2.8       0.0       5.1          43.0   

        counts  
342990     3.0  
342991     4.0  
342992     0.0  
342993     2.0  
342994     1.0

In [27]:
fire_ml.isnull().sum()

area_code       0
date            0
max_temp        0
day_rain        0
max_wind        0
min_humidity    0
counts          0
dtype: int64

In [29]:
features = fire_ml[['max_temp','day_rain','max_wind','min_humidity']]
counts = fire_ml[['counts']]

In [30]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, counts , test_size=0.33, random_state=321)


In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_features = scaler.fit_transform(train_features)
test_features = scaler.fit_transform(test_features)

In [34]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(train_features, train_labels)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [35]:
model.score(train_features, train_labels)

0.9276346135435977

In [36]:
model.score(test_features, test_labels)

0.9258673546015955

In [38]:
model.coef_

array([[-0.01389542,  1.10525114,  0.63959103,  0.62925709],
       [-0.01411829,  1.09251879,  0.70998315,  0.28498953],
       [-0.12267078,  0.9885666 ,  0.66634308,  0.41398006],
       [-0.07841046,  0.96298948,  0.54691801,  0.37276844],
       [-0.15537351,  1.01360783,  0.42328586,  0.27985268],
       [ 0.03104533,  0.41897695,  0.60495139,  0.11302522],
       [-0.07587082, -1.06124549,  0.59880033,  0.13144585],
       [-0.07592999,  0.56591433,  0.47177583, -0.08302733],
       [ 0.03197536, -1.04678515,  0.77799167, -0.17178308],
       [-0.10915628, -0.8927277 ,  0.68617377, -0.00605425],
       [ 0.14902016, -0.53437825,  0.8680628 , -0.48411928],
       [ 0.28500006, -0.63539396,  0.65684758, -0.26119664],
       [ 0.31107537, -0.62324524,  0.88790187, -0.68264506],
       [-0.04479625, -0.87384914,  0.14895627,  0.22137496],
       [ 0.18111733, -0.83058291,  1.02061146,  0.38936434],
       [ 0.16432896, -0.78257005,  0.8458119 , -0.37521215],
       [ 0.32786291, -0.

In [39]:
train_features

array([[ 1.61155923, -0.15687998, -0.71641594, -0.16327013],
       [-1.35665621, -0.26825668,  0.13912703, -1.22653842],
       [ 0.18886286, -0.26825668, -1.30178744, -0.97337931],
       ...,
       [ 0.44474351, -0.26825668,  0.27421276, -0.56832472],
       [-1.64324253, -0.223706  ,  0.63444138,  0.79873452],
       [-0.10795868, -0.26825668,  2.57067019,  0.39367993]])

In [209]:
import numpy as np
import random 
day = []
for i in range(1000) :
    day.append([])
    rand_max_temp = round(random.uniform(fire_ml['max_temp'].min(), fire_ml['max_temp'].max()),1)
    rand_day_rain = round(random.uniform(fire_ml['day_rain'].min(), fire_ml['day_rain'].max()),1)
    rand_max_wind = round(random.uniform(fire_ml['max_wind'].min(), fire_ml['max_wind'].max()),1)
    rand_min_humidity = round(random.uniform(fire_ml['min_humidity'].min(), fire_ml['min_humidity'].max()),1)
    
    
    
    day[i] = np.array([float(str(rand_max_temp).strip())
                 ,float(str(rand_day_rain).strip())
                 ,float(str(rand_max_wind).strip())
                 ,float(str(rand_min_humidity).strip())])

    print(day[i])
    
    #day[i] = np.array(day[i]).reshape(-1,1)
    #np.reshape(day[i], (1, -1))




[  6.2 198.8  37.4  66.2]
[  7.5 341.   41.5  28.7]
[ 17.6 162.2  27.   97.7]
[29.2 23.1 20.8 33.5]
[  5.3 206.   28.5  34.6]
[ 10.8 389.3   5.3  72.2]
[  4.  144.9  47.1  43. ]
[-10.2 364.2  32.5  24.6]
[ 10.2 227.2   9.   67.4]
[ 13.6 211.4  42.7   9.8]
[ 23.9 361.6  37.3  18.9]
[-11.7 306.3  19.2  81.5]
[  2.9 281.7  15.1   3.4]
[ 38.9 108.   32.2  61.7]
[20.   4.5  7.6 57.8]
[ 23.9 387.2  31.8  57. ]
[-12.6 372.8  14.2  43.3]
[ 33.5 194.9  15.9  53.1]
[ 16.7 336.1  35.3  49.1]
[33.   9.1 44.4 50.3]
[-10.3 101.5  36.6  87.5]
[ 12.2 166.8  21.4  86.4]
[ -1.7 347.8  17.8  68.6]
[  3.1 279.1  35.6  18. ]
[36.9 31.1  7.4 79.4]
[31.4 74.1 44.8 18.2]
[-6.6 44.9 27.  90.5]
[ 22.4 270.1  33.9  86.3]
[-11.3 171.1   6.5  67. ]
[  3.9 222.5  20.8  69.5]
[ 30.2 322.9  48.   70.4]
[ 20.1 168.1  34.7  95.6]
[ 19.4 313.1  13.4  99.3]
[ 27.1 122.4  29.3  43.3]
[ 27.1 283.1  11.4  68. ]
[ 32.1 188.2  24.7  37.1]
[ -4.7 352.1   7.5  27.4]
[ 6.3 94.7 37.7 37.9]
[36.1 49.9 48.2 84. ]
[2.230e+01 1.408e+

In [260]:
test = np.array([float(str(rand_max_temp).strip())
                 ,float(str(rand_day_rain).strip())
                 ,float(str(rand_max_wind).strip())
                 ,float(str(rand_min_humidity).strip())])
#test = np.array(test).reshape(-1,1)
sample_data = np.array([test])
scaler = StandardScaler()
scaler.fit(sample_data)
sample_data = scaler.transform(sample_data)
model.predict(sample_data)


array([1.])


In [261]:
test = np.array([float(str(rand_max_temp).strip())
                 ,float(str(rand_day_rain).strip())
                 ,float(str(rand_max_wind).strip())
                 ,float(str(rand_min_humidity).strip())])
#test = np.array(test).reshape(-1,1)
sample_data = np.array([test])
scaler = StandardScaler()
scaler.fit(sample_data)
sample_data = scaler.transform(sample_data)
model.predict(sample_data)


array([0.])

In [206]:
#각 데이터 포인트에 대한 클래스 확률을 반환하는 방법
model.predict_log_proba(sample_data)


array([[ -0.06595494,  -3.50317583,  -4.37443296,  -4.89316418,
         -5.27695035,  -5.79906667,  -6.80321103,  -6.58706213,
         -7.42602869,  -7.52404068,  -8.25129005,  -7.98129333,
         -9.11981313,  -8.58154378,  -8.81950152,  -8.65504354,
         -9.89825129, -10.25699236,  -9.74197347, -10.36888045,
        -11.45853013, -11.21715   , -11.21486629, -11.44070766,
        -10.23254841, -10.81049819, -11.15573925, -11.56772149,
        -11.46591738, -10.71426758, -11.60947213, -11.56104151,
        -11.89351918, -11.6862645 , -10.88521498, -12.1330192 ,
        -11.14844645, -11.13432302, -11.22330678, -10.77653904,
        -12.1396667 , -11.687374  , -11.13727572, -11.24330108,
        -12.1455889 , -11.47403191, -11.40049617, -11.07536272,
        -11.67536419, -11.23249901, -10.97722607, -10.49675827,
        -11.06678526, -11.28101251, -11.30024942]])